name = "Better Building"
author = "O4bit"
version = "8.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "651983102cf1bfd9fa02595b6a2ac8b2605c346deaef0f818ae812d7e3d319db"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"
