name = "Better Building"
author = "O4bit"
version = "8.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5732b712e8f0b0cd72da8014ae663199cad3102cc843a81ef35e0ae5e6e1c12"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.224"
