name = "Better Building"
author = "O4bit"
version = "8.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95ee23b5f7490772369328b43def2b46def8e97e95ae5d74366b871efb5fd84f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"
